### ISSUE TITLE
Multiple Child Nodes

### ISSUE THREAD

**Issue by liko28s** [apidoc/apidocjs.com#12]
there is a way to send multiple child nodes in a json (multidimensional array) in the Request Example?
for example:
{
         "person1": {"id": "1", "name1", "John", "name2": "steven", "lastname", "jhonson"},
         "person2": {"id", "2", "name1", "Marly", "name2", "jay", "lastname", "jackson"}
}

**Comment by rottmann** [comment]
The test library is really rudimentary and will be replaced. Currently you can only test really simple requests.

Follow up the other [sample request issues](https://github.com/apidoc/apidoc/milestones/Send%20sample%20request%20plugin)
