### ISSUE TITLE
Disable AutoSort

### ISSUE THREAD

**Issue by jekku** [apidoc/apidocjs.com#13]
I want to disable autosorting of my documentation entries. Is that possible?

**Comment by rottmann** [comment]
You can set a manual sort order http://apidocjs.com/#configuration-settings in apidoc.json

**Comment by jekku** [comment]
Not what I expected for an answer, but still useful information. Thanks.

**Comment by Washiul** [comment]
when i try to create an api document, the output gets very awkward format. how to fix it?
