### ISSUE TITLE
Generating Navagation Links Using Method Type and @apiName Instead of Description

### ISSUE THREAD

**Issue by pihish** [apidoc/apidocjs.com#17]
When I generate my API documentation, the links to each individual API on the left hand side of the index page are currently being generated from the description of the API.

```
@api {post} /my/endpoint **this is the current link name**
```

I would like the link name to be a combination of the method type (in the above example _post_) and the @apiName.  For this block comment:

```
@api {post} /my/endpoint description of API
@apiName Create Cake
```

I would like the link text for that API to be _POST - Create Cake_

Is there anyway to do this?

**Comment by rottmann** [comment]
Funny, never got an email of new issues or pull requests for apidocjs.com Website, until today.
Please post you issue to apidoc project, if it is still a problem https://github.com/apidoc/apidoc
