### ISSUE TITLE
Spanish version

### ISSUE THREAD

**Issue by CodersBrothers** [apidoc/apidocjs.com#2]
I can translate apidocjs.com and pull request a file like index_es.html
Are you agree?

**Comment by rottmann** [comment]
You mean `locales/es.js` file? Or did i oversee a text-string in index.html?

I see some other made translations too (chinese, dutch), would be nice, i will integrate them all.

**Comment by CodersBrothers** [comment]
mmmmm, i say translate apidocjs.com, this file: https://github.com/apidoc/apidocjs.com/blob/gh-pages/index.html For do a little better integration and consideration of spanish language developers.

I say create index_es.html because it's indexable and most easy that integrate a locale js way process.

**Comment by rottmann** [comment]
Oh my god, much work. I think at the moment we keep one language and make the docs better and easier to read and understand.

**Comment by CodersBrothers** [comment]
Yes, so maybe i will do one article in some blog explaining how use in spanish. Only for lazy people. More easy = more developers :D

**Comment by rottmann** [comment]
That would be a good idea. I think articles about HowTo use it will help the project.
