### ISSUE TITLE
parser plugin 'apidefinepermission' not found in block: 1

### ISSUE THREAD

**Issue by jeesus** [apidoc/apidocjs.com#23]
Hey

According to the [example_full](http://apidocjs.com/source/example_full/_apidoc.js), there should be a method to define permissions with `@apiDefinePermission`. Unfortunately all I get using that is following:
```
warn: parser plugin 'apidefinepermission' not found in block: 1
warn: parser plugin 'apidefinepermission' not found in block: 2
warn: parser plugin 'apidefinepermission' not found in block: 3
```
It will work though when using just `@apiDefine`. So what am I missing? Do I have to load extra plugins or what? My `_apidoc.js` is a complete copy of the example, so no tampering with the markup.

**Comment by jam0ral3s** [comment]
Change  @apiDefinePermission to @apiDefine and it works

**Comment by jeesus** [comment]
That's right. Also figured it out some time ago. Should update the docs then though.
