### ISSUE TITLE
"Integrated is an API history" sentence

### ISSUE THREAD

**Issue by harry-wood** [apidoc/apidocjs.com#32]
The second sentence on the website:

"Integrated is an API history, with that various API version levels can be compared. So it can be retraced what changed in the API since the last version."

...needs to be rephrased. It doesn't actually make sense

**Comment by NicolasCARPi** [comment]
While I agree that it should be rephrased, it does make sense.

New sentence could be : "apidoc gives you the ability to attach a version number to an API so you can easily track changes between versions."

**Comment by rottmann** [comment]
Changed. Thank you.
