### ISSUE TITLE
apiBody is not in the index of the documentation

### ISSUE THREAD

**Issue by MiguelVis** [apidoc/apidocjs.com#38]
Hi all.

Regarding merged PR #34 it seems that the item `@apiBody` is missing in the list under apiDoc-Params:

```
apiDoc-Params
@api
@apiDefine
@apiDeprecated
...
```

The content of `@apiBody` is in place but the examples appear as `@apiParam` instead of `@apiBody`.

**Comment by NicolasCARPi** [comment]
Thanks!

**Comment by MiguelVis** [comment]
Sorry but this remains the same:

> ...but the examples appear as @apiParam instead of @apiBody.

Even more, the information shown is wrong / inconsistent (marked some as bold):

> **@apiBody [{type}] [field=defaultValue] [description]**
> Describe the request body passed to your API-Method.
> 
> **Usage: @apiBody {type} {key: value}**
> ...
> /**
>  * @api {get} /user/:id
>  * **@apiParam {Number} id Users unique ID.**
>  */
> 
> /**
>  * @api {post} /user/
>  * **@apiParam {String} [firstname]       Optional Firstname of the User.**
>  * @apiParam {String} lastname          Mandatory Lastname.
>  * @apiParam {String} country="DE"      Mandatory with default value "DE".
> ...

**Comment by NicolasCARPi** [comment]
Would you care doing a PR?

**Comment by MiguelVis** [comment]
Ok, I will try to do it asap.
