### ISSUE TITLE
Lefthand navigation doesn't scroll

### ISSUE THREAD

**Issue by markstos** [apidoc/apidocjs.com#4]
Looking at the web page on a small screen, it's a problem that the left hand navigation never scrolls if it taller than the screen.  It's impossible to find the bottom of the list of API parameters in that case. 

Noticed using Chrome and Explorer on a Surface tablet by @robludwig

**Comment by rottmann** [comment]
I will change it and remove the scroll stopper on the next release, in the first releases less commands exists, so it was no problem.

**Comment by markstos** [comment]
Thanks!

On Thu, Sep 18, 2014 at 11:37 AM, Peter Rottmann notifications@github.com
wrote:

> I will change it and remove the scroll stopper on the next release, in the
> first releases less commands exists, so it was no problem.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/apidoc/apidocjs.com/issues/4#issuecomment-56057024.

## 

```
Mark Stosberg
Senior Systems Engineer
RideAmigos
```
