### ISSUE TITLE
@apiDeprecated

### ISSUE THREAD

**Issue by baptistedonaux** [apidoc/apidocjs.com#7]
I'm newbie on apidocjs but I would like use it to generate the API documentation. I found all options necessary except one to mark one method like deprecated.

Thank you for your help. (Great project !)

**Comment by rottmann** [comment]
I set it on the ToDo-List https://github.com/apidoc/apidoc/wiki/ToDo

**Comment by baptistedonaux** [comment]
+1

**Comment by sankar4n** [comment]
+1

**Comment by xuxin0612** [comment]
+1
